course/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/course/',views.AddCourse.as_view(),name='addcourse'),
    path('add/<slug:slug>/chapter/',views.AddChapter.as_view(),name='addchapter'),
    path('add/<slug:slug>/test/',views.AddTest.as_view(),name='addtest'),
    path('update/<slug:slug>/course/',views.UpdateCourse.as_view(),name='updatecourse'),
    path('update/<slug:slug>/chapter/<int:pk>',views.UpdateChapter.as_view(),name='updatechapter'),
    path('update/<slug:slug>/test/<int:pk>',views.UpdateTest.as_view(),name='updatetest'),
    path('delete/<slug:slug>/course/',views.DeleteCourse.as_view(),name='deletecourse'),
    path('delete/<slug:slug>/chapter/<int:pk>',views.DeleteChapter.as_view(),name='deletecourse'),
    path('delete/<slug:slug>/test/<int:pk>',views.DeleteTest.as_view(),name='deletecourse')
]

learnetV_2_1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from learnetV_2_1.settings import STATIC_URL,STATICFILES_DIRS,MEDIA_URL,MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('userlog.urls')),
    path('student/',include('student.urls')),
    path('teacher/',include('teacher.urls')),
    path('course/',include('course.urls')),
]

urlpatterns += static(STATIC_URL,document_root=STATICFILES_DIRS)
urlpatterns += static(MEDIA_URL,document_root=MEDIA_ROOT)

student/urls.py
from django.urls import path

from student import views

urlpatterns = [
    path('dashboard/',views.StudentDashboard.as_view(),name='student_dashboard'),
    path('dashboard/<str:error>',views.StudentDashboard.as_view(),name='student_dashboard_error'),
    path('many/courses/',views.AllCourses.as_view(),name='many_course'),
    path('course/<slug:slug>/',views.SingleCourse.as_view(),name='enroll'),
    path('read/course/<slug:slug>/chapter/<int:pk>/<str:chapterName>/',views.ReadCourse.as_view(),name='read_course'),
    path('give/course/<slug:slug>/test/<int:pk>/<str:title>/',views.GiveTest.as_view(),name='give_test'),
    path('contact/',views.StudentContact.as_view(),name='student_contact'),
    path('many/course',views.StudentManyCourse.as_view(),name='student_many_course'),
]

userlog/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError
import os
from django.db import models

def profile_pic_file_path(instance, filename):
    # Generate a unique image name based on the username
    if filename is None:
        raise ValidationError('Upload a file')
    base_filename, file_extension = os.path.splitext(filename)
    ext = file_extension.lower()
    allowed_extensions = ['.png', '.jpg', '.jpeg']
    if ext not in allowed_extensions:
        raise ValidationError('Only .png, .jpg or .jpeg extenstions are allowed.')
    return f'profilepic/{instance.username}{file_extension}'

class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(username=username,email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, username, email, password=None):
        user = self.create_user(username, email, password=password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=100,unique=True)
    profilepic = models.ImageField(default='profilepic\profile.jpg',upload_to=profile_pic_file_path)
    role = models.BooleanField(default=False)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    date_joined = models.DateTimeField(default=timezone.now)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.username
    
class MailToken(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    token = models.CharField(max_length=100)

student/forms.py
from django import forms
from .models import Student,UserPreference
from django.core.validators import RegexValidator

class UserInformationForm(forms.ModelForm):
    first_name = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'placeholder': 'First Name'}),required=False)
    last_name = forms.CharField(max_length=30,widget=forms.TextInput(attrs={'placeholder': 'Last Name'}),required=False)

    class Meta:
        model = Student
        fields = '__all__'
        exclude = ['user']

    phone = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Phone Number'
        }),
        required=False,
        validators=[
            RegexValidator(
                '(\+977)?[9][6-9]\d{8}',
                message='Phone Number should be in "+977-9800000000"'
            )]
        )
    city = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Enter Your City Name'}), required=False,)
    district = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Enter Your District Name'}), required=False,)
    state = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'placeholder': 'Enter Your State Name'}), required=False,)

    def clean(self):
        cleaned_data = super().clean()
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if not first_name:
            raise forms.ValidationError('First Name field is required')
        if not last_name:
            raise forms.ValidationError('Last Name field is required')
        
        return cleaned_data
            

class UserPreferenceForm(forms.ModelForm):
    
    class Meta:
        model = UserPreference
        fields = '__all__'
        exclude = ['user']

    html = forms.BooleanField(required=False,label='html',widget=forms.CheckboxInput())
    css = forms.BooleanField(required=False,label='css',widget=forms.CheckboxInput())
    javascript = forms.BooleanField(required=False,label='javascript',widget=forms.CheckboxInput())
    python = forms.BooleanField(required=False, label='python',widget=forms.CheckboxInput())
    data_analysis = forms.BooleanField(required=False, label='data analysis',widget=forms.CheckboxInput())
    data_structure_and_algorithms = forms.BooleanField(required=False, label='data structure and algorithms',widget=forms.CheckboxInput())
    natural_language_processing = forms.BooleanField(required=False, label='natural language processing',widget=forms.CheckboxInput())
    machine_learning = forms.BooleanField(required=False,label='machine learning',widget=forms.CheckboxInput())

course/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.utils.text import slugify
import json

from .models import Course, Chapter, Test
from .forms import CourseForm, ChapterForm, TestForm
from .validations import course_validate, chapter_validate, test_validate
from .next_object import get_next_chapter,get_next_test
from teacher.models import Teacher
from userlog.models import CustomUser

# Create your views here.
class AddCourse(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    template_name = 'addCourse.html'
    model = Course
    form_class = CourseForm
    context_object_name = 'pic'

    def dispatch(self, request, *args, **kwargs):
        try:
            Teacher.objects.get(user=request.user)
        except:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        pic = CustomUser.objects.get(username=self.request.user.username).profilepic
        context['pic'] = pic
        return context

    def form_invalid(self, form):
        error_msg_dict = json.loads(form.errors.as_json())
        error = course_validate(error_msg_dict)
        return render(self.request, self.template_name, {'form': form, 'error': error})
    
    def form_valid(self, form):
        teacher = Teacher.objects.get(user=self.request.user)
        form.instance.teacher = teacher
        course_title = form.cleaned_data['courseTitle']
        
        if Course.objects.filter(courseTitle=course_title).exists():
            form.add_error('courseTitle', 'Course With This Name Already Exists')
            return self.form_invalid(form)
        
        response = super().form_valid(form)
        return response

    def get_success_url(self):
        form = self.request.POST
        return reverse('addchapter', kwargs={'slug': slugify(form.get('courseTitle'))})


class AddChapter(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    template_name = 'addChapter.html'
    model = Chapter
    form_class = ChapterForm

    def dispatch(self, request, *args, **kwargs):
        try:
            Teacher.objects.get(user=request.user)
        except:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        pic = CustomUser.objects.get(username=self.request.user.username).profilepic
        context['pic'] = pic
        return context
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = Teacher.objects.get(user=self.request.user)
        courses = Course.objects.filter(teacher=user)
        kwargs['teacher_courses'] = courses
        return kwargs
    
    def get_initial(self):
        initial = super(AddChapter, self).get_initial()
        initial['course'] = Course.objects.get(slug=self.kwargs['slug'])
        return initial

    def form_invalid(self, form):
        error_msg_dict = json.loads(form.errors.as_json())
        error = chapter_validate(error_msg_dict)
        return render(self.request, self.template_name, {'form': form, 'error': error})
    
    def get_success_url(self):
        form = self.request.POST
        course = Course.objects.get(slug=self.kwargs['slug'])
        # next takes to add test
        if form.get('next'):
            return reverse_lazy('addtest', kwargs={'slug': course.slug})
        # add_more takes to add another chapter
        if form.get('add_more'):
            return reverse('addchapter', kwargs={'slug': course.slug})


class AddTest(AddChapter):
    login_url = '/login/'
    template_name = 'addTest.html'
    model = Test
    form_class = TestForm

    def dispatch(self, request, *args, **kwargs):
        try:
            Teacher.objects.get(user=request.user)
        except:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        pic = CustomUser.objects.get(username=self.request.user.username).profilepic
        context['pic'] = pic
        return context
    
    def get_initial(self):
        initial = super(AddChapter, self).get_initial()
        initial['course'] = Course.objects.get(slug=self.kwargs['slug'])
        return initial

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = Teacher.objects.get(user=self.request.user)
        courses = Course.objects.filter(teacher=user)
        kwargs['teacher_courses'] = courses
        return kwargs
    
    def form_invalid(self, form):
        error_msg_dict = json.loads(form.errors.as_json())
        error = test_validate(error_msg_dict)
        return render(self.request, self.template_name, {'form': form, 'error': error})
    
    def get_success_url(self):
        form = self.request.POST
        course = Course.objects.get(slug=self.kwargs['slug'])
        # next takes to add test
        if form.get('publish'):
            course.published = True
            course.save()
            return '/teacher/dashboard/'
        # add_more takes to add another chapter
        if form.get('add_more'):
            return reverse('addtest', kwargs={'slug': course.slug})


class UpdateCourse(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    template_name = 'updateCourse.html'
    model = Course
    form_class = CourseForm

    def get_success_url(self):
        course = self.model.objects.get(slug=self.object.slug)
        slug = course.slug
        try:
            pk = Chapter.objects.filter(course=course).first().pk
        except AttributeError:
            return reverse_lazy('addchapter', kwargs={'slug': slug})
        return reverse_lazy('updatechapter', kwargs={'slug': slug, 'pk': pk})

    def dispatch(self, request, *args, **kwargs):
        try:
            Teacher.objects.get(user=request.user)
        except:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['pic'] = self.request.user.profilepic
        return context
    
    def form_invalid(self, form):
        error_msg_dict = json.loads(form.errors.as_json())
        error = course_validate(error_msg_dict)
        return render(self.request, self.template_name, {'form': form, 'error': error})


class UpdateChapter(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    template_name = 'updateChapter.html'
    model = Chapter
    form_class = ChapterForm

    def dispatch(self, request, *args, **kwargs):
        try:
            Teacher.objects.get(user=request.user)
        except:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
 
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = Teacher.objects.get(user=self.request.user)
        courses = Course.objects.filter(teacher=user)
        kwargs['teacher_courses'] = courses
        return kwargs
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = Course.objects.get(slug=self.kwargs['slug'])
        context['chapter'] = Chapter.objects.get(id=self.kwargs['pk'])
        context['pic'] = self.request.user.profilepic
        return context

    def form_invalid(self, form):
        error_msg_dict = json.loads(form.errors.as_json())
        error = chapter_validate(error_msg_dict)
        return render(self.request, self.template_name, {'form': form, 'error': error})
    
    def get_success_url(self):
        form = self.request.POST
        course = Course.objects.get(slug=self.kwargs['slug'])
        # next takes to another chapter
        if form.get('next'):
            next_chapter = get_next_chapter(course,self.kwargs['pk'])
            if not next_chapter:
                return reverse('addchapter', kwargs={'slug': course.slug})
            else:
                return reverse('updatechapter', kwargs={'slug': course.slug, 'pk': next_chapter.pk})
        # add_more takes to update test or add test
        if form.get('add_more'):
            try:
                pk = Test.objects.filter(course=course).first().pk
            except AttributeError:
                return reverse_lazy('addtest', kwargs={'slug': course.slug})
            
            return reverse_lazy('updatetest', kwargs={'slug': course.slug, 'pk': pk})
    
class UpdateTest(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    template_name = 'updateTest.html'
    form_class = TestForm
    model = Test

    def dispatch(self, request, *args, **kwargs):
        try:
            Teacher.objects.get(user=request.user)
        except:
            return redirect('login')
        return super().dispatch(request, *args, **kwargs)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user = Teacher.objects.get(user=self.request.user)
        courses = Course.objects.filter(teacher=user)
        kwargs['teacher_courses'] = courses
        return kwargs
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['course'] = Course.objects.get(slug=self.kwargs['slug'])
        context['test'] = Test.objects.get(id=self.kwargs['pk'])
        context['pic'] = self.request.user.profilepic
        return context

    def form_invalid(self, form):
        error_msg_dict = json.loads(form.errors.as_json())
        error = test_validate(error_msg_dict)

student/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static '/css/style.css' %}" />
    <link rel="stylesheet" href="{% static '/css/dashboard.css' %}" />
    <link rel="shortcut icon" href="{% static '/img/favicon.png' %}" type="image/png" />
    <title>
      {% block title %}

      {% endblock %}
    </title>
  </head>
  <nav>
    <div class="nav-title">
      <a href="{% url 'home' %}">Learnet</a>
    </div>
    <div class="nav-links">
      <ul class="nav-menu">
        <li>
          <a href="{% url 'home' %}" class="nav-link">Home</a>
        </li>
        <li>
          <a href="{% url 'many_course' %}" class="nav-link">Courses</a>
        </li>
        <li>
          <a href="{% url "student_contact" %}" class="nav-link">Contact</a>
        </li>
        {% if user.is_authenticated %}
          <li class="profile-img">
            <img src="{{ pic.url }}" alt="Profile Image" />
            <ul class="profile-links">
              <li>
                <a href="{% url 'student_dashboard' %}">Dashboard</a>
              </li>
              <li class="login">
                <a href="{% url 'logout' %}">Log-Out</a>
              </li>
            </ul>
          </li>
        {% else %}
          <li class="login">
            <a href="{% url 'login' %}" class="nav-link">Log-In</a>
          </li>
        {% endif %}
      </ul>
      <div class="hamburger">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
      </div>
    </div>
  </nav>

  <body>
    {% block content %}

    {% endblock %}
  </body>
  <footer>
    <div class="img">
      <img src="{% static '/img/logo.png' %}" alt="Learnet Company Logo" />
    </div>
    <div class="foot">
      <div class="footer-title">
        <h3>Social link:</h3>
      </div>
      <div>
        <div>
          <img src="{% static '/img/fb.png' %}" alt="Nepal Padhcha Facebook" />
          <a href="#">Facebook</a>
        </div>
        <div>
          <img src="{% static '/img/yt.png' %}" alt="Nepal Padhcha YouTube" />
          <a href="#">YouTube</a>
        </div>
        <div>
          <img src="{% static '/img/twitter.png' %}" alt="Nepal Padhcha Twitter" />
          <a href="#">Twitter</a>
        </div>
        <div>
          <img src="{% static '/img/email.png' %}" alt="Nepal Padhcha Twitter" />
          <a href="#">E-mail</a>
        </div>
      </div>
    </div>
    <div class="foot">
      <div class="footer-title">
        <h3>Courses:</h3>
      </div>
      <div>
        <div>
          <img src="{% static '/img/book1.png' %}" alt="Nepal Padhcha Facebook" />
          <a href="singleCourse.html">Course</a>
        </div>
        <div>
          <img src="{% static '/img/book2.png' %}" alt="Nepal Padhcha YouTube" />
          <a href="singleCourse.html">Course</a>
        </div>
        <div>
          <img src="{% static '/img/book3.png' %}" alt="Nepal Padhcha Twitter" />
          <a href="singleCourse.html">Course</a>
        </div>
        <div>
          <img src="{% static '/img/book4.png' %}" alt="Nepal Padhcha Twitter" />
          <a href="singleCourse.html">Course</a>
        </div>
      </div>
    </div>
  </footer>

  <script src="{% static '/js/script.js' %}"></script>
</html>

student/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Contact - Learnet
{% endblock %}
{% block content %}
  <div class="container">
    <div class="contact-page">
      <div>
        <h1>Let's have a talk</h1>
      </div>
      <div>
        <form method="post">
          {% csrf_token %}
          <div>{{ form.username }}</div>
          {% if error.username %}
            <p class="error">{{ error.username }}</p>
          {% endif %}
          <div>{{ form.email }}</div>
          {% if error.email %}
            <p class="error">{{ error.email }}</p>
          {% endif %}
          <div>{{ form.message }}</div>
          {% if error.message %}
            <p class="error">{{ error.message }}</p>
          {% endif %}
          <div>
            <button type="submit" class="sub-btn">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

student/templates/course.html
{% extends "studentbase.html" %}
{% load static %}
{% block title %}Course - learnet{% endblock title %}
{% block content %}
<div class="read-course-container">
    <div class="read-course">
        <div class="chapter-list-container">
            <div class="chapter-list">
                <ul class="chap-menu">
                    {% if chapters %}
                        {% for chapter in chapters %}
                            <li><a href="{% url 'read_course' chapter.course.slug chapter.id chapter.chapterName%}" class="nav-link">{{ chapter.chapterName }}</a></li>
                        {% endfor %}
                    {% endif %}
                    <p>Tests &#8595</p>
                    {% if tests %}
                        {% for test in tests %}
                            <li><a href="{% url  'give_test' course.slug test.max_id test.title %}" class="nav-link">{{ test.title }}</a></li>
                        {% endfor %}
                    {% endif %} 
                </ul>
            </div>
        </div>
        <div class="read-chapter">
            <div class="read-chapter-title">
                <h1>{{ chapter.chapterName }}</h1>
            </div>
            <div class="read-chapter-body">         
                <pre>{{ chapter.chapterBody | safe }}</pre>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

student/templates/manycourse.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  All Courses - Learnet
{% endblock %}
{% block content %}
  <div class="container">
    <div class="many-course-container">
      <div class="many-course-contains">
        {% if courses %}
          {% for course in courses %}
            <div class="many-course">
              <div class="many-course-img">
                <img src="{{ course.courseImage.url }}" alt="{{ course.courseTitle }}" />
              </div>
              <div class="many-course-body">
                <div>
                  <h1>{{ course.courseTitle }}</h1>
                  {% if course.courseDescrip|length > 100 %}
                    <p class="course-descrip">{{ course.courseDescrip|slice:':100' }}...</p>
                  {% else %}
                    <p class="course-descrip">{{ course.courseDescrip }}</p>
                  {% endif %}
                </div>
              </div>
              <div class="many-course-enroll">
                <a href="{% url "enroll" course.slug %}" class="enroll">Enroll</a>
              </div>
            </div>
          {% endfor %}
        {% endif %}
        <div class="pagination">
          <span class="step-links">
            {% if page_obj.has_previous %}
              <a href="?page=1">&laquo; 1 -</a>
              <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">{{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span>

            {% if page_obj.has_next %}
              <a href="?page={{ page_obj.next_page_number }}">next -</a>
              <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
          </span>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

student/templates/singleCourse.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  {{course.courseTitle}}
{% endblock %}
{% block content %}
  <div class="container">
    <div class="single-course">
      <div class="single-course-heading">
        <div class="single-course-title">
          <div>
            <img src="{{ course.courseImage.url }}" alt="{{ course.courseTitle }}" />
          </div>
          <div>
            <h1>{{ course.courseTitle }}</h1>
          </div>
        </div>
        <div>
          <a href="{% url 'read_course' course.slug chapter.pk chapter.chapterName %}" class="enroll">Enroll Now</a>
        </div>
      </div>
      <div class="course-description">
        <div class="descrip">
          <div>
            <h1>Course Description:</h1>
          </div>
          <div>
            <pre>{{ course.courseDescrip }}</pre>
          </div>
        </div>
        <div class="author">
          <div>
            <h3>Author:</h3>
            <p>{{ course.teacher }}</p>
          </div>
          <div>
            <a href="{% url 'read_course' course.slug chapter.pk chapter.chapterName %}" class="enroll">Enroll Now</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

student/templates/studash.html
{% extends 'studentbase.html' %}
{% load static %}
{% block title %} Student - Dashboard {% endblock%}
{% block content %}
<div class="container">
    <div class="container-content">
        <div class="std-courses">
            <div class="course-head">
                <div>
                    <h1>Your Courses</h1>
                </div>
            </div>
            {% if enrolls is None %}
                <div class="no-course">
                    <h2>You are not enrolled in any courses <a href="{% url "many_course" %}" class="enroll">Click here </a>to enroll</h2>
                </div>
            {% else %}
            <div class="course-container">
                {% for enroll in enrolls  %}
                    <div class="course-card">
                        <div>
                            <img src="{{ enroll.course.courseImage.url }}" alt="{{enroll.course.courseImage.url}}">
                        </div>
                        <div>
                            <h1>
                                {% if enroll.course.courseTitle|length > 11 %}
                                    {{ enroll.course.courseTitle|slice:":10" }}...
                                {%else %}
                                    {{ enroll.course.courseTitle }}
                                {% endif %}
                            </h1>
                            <div class="course-link">
                                <a href="{% url "enroll" enroll.course.slug %}" class="edit">Read</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="more-course">
                <a href="{% url "student_many_course" %}">View More</a>
            </div>
            {% endif %}
        </div>
        <div class="user-information">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="personal-details">
                    <div class="personal-details-content">
                        <div class="personal-head">
                            <h1>Personal Details</h1>
                        </div>
                        <div class="personal-body">
                            <div class="details">
                                <div class="profile-picture-field">
                                    <img class="profile-picture" src="{{ pic.url }}">
                                    <input type="file" name="profilepic" accept="image/*" id="id_profilepic" value="{{ pic.profilepic.url }}">
                                </div>
                                <div>
                                    <div class="std-name">
                                        {{ userform.first_name }}
                                        {{ userform.last_name }}
                                    </div>
                                    <div>
                                        {{ userform.phone }}
                                    </div>
                                    {% if error %}
                                    <div class="error">
                                        <p>{{ error }}</p>
                                    </div>
                                    {% endif %}
                                    <div>
                                        <a href="#" class="change-pass">Change Password?</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="user-address">
                        <div class="address">
                            <h1>Address</h1>
                            {{ userform.city }}
                            {{ userform.district }}
                            {{ userform.state }}
                        </div>
                    </div>
                    <div class="user-edu">
                        <h1>Education</h1>
                        {{ userform.edubackground }}
                    </div>
                    <div class="preference">
                        <div class="select-preference">
                            <div class="user-pref">
                                <p>Choose Skill You Want To Learn:</p>
                            </div>
                            <div class="categories">
                                {{prefform.label}}
                                {{ prefform.as_p }}
                            </div>
                        </div>
                    </div>
                    <div class="update-details">
                        <button type="submit">Update Details</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}